### ISSUE TITLE
CONVERSIONES YANET

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/ejercicios-eq-erick-yanet-lourdes-1as#2]
[CONVERSIÓN DECIMAL A BINARIO-EQUIPO..pdf](https://github.com/SistemasTecTlaxiaco/ejercicios-eq-erick-yanet-lourdes-1as/files/7149844/CONVERSION.DECIMAL.A.BINARIO-EQUIPO.pdf)

**Comment by yaritzaov123** [comment]
el trabajo esta bien elaborado y cumple con todos lo establecido en la rubrica se merece el 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
