### ISSUE TITLE
Ejercicios

### ISSUE THREAD

**Issue by Erick-3as** [SistemasTecTlaxiaco/ejercicios-eq-erick-yanet-lourdes-1as#3]
[CONVERSIÓN DECIMAL A BINARIO-EQUIPO..pdf](https://github.com/SistemasTecTlaxiaco/ejercicios-eq-erick-yanet-lourdes-1as/files/7150016/CONVERSION.DECIMAL.A.BINARIO-EQUIPO.pdf)

**Comment by JulioCGz** [comment]
el trabajo estuvo bien elaborado se merece el 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
